CRACK = (('$', 's'),('&', 'and'), ('@', 'a'), ('0', 'o'), ('1', 'i'), ('|', 'I'), ('€', 'E'), ('(', 'C'), ('|<', 'K'))

def crackcode(code):
	for a,b in CRACK:
		code = code.replace(a, b)
	return code

if __name__ == "__main__":
	crack = input("Enter the code to crack(must be made by code.py file):\n")
	crack = crackcode(crack)
	print(f"Your cracked code is\n{crack}\n")

input("Please enter your feedback: ")
print("Thank you for your feedback")

###########################		How to Use		############################
'''
NOTE = The code will only be cracked when it is made by the code.py

How to use this code cracker tool :-

1. If you forget the code which you have generated by the code.py then you should type 'python cracker.py' in the dir where you saved this python file.
2. Then Paste the code there.
3. And you are all done the code is now cracked.
'''